#
#       Parameter Estimation:
#
# Simple case: no movement so we consider just one block, no NK and no ODC irreversible damage!
# We want to see:
#   1) After 50 days the EBV is gone
#   2) In 14 days the Teff cells reach their max value (20-30 000)
#   3) After 10 days everything comes back to the normality!
#
###################################################################
#This file is automatically generated by Greatspn                 #
#You can report bugs  by sending an e-mail to beccuti@di.unito.it #
###################################################################


library(deSolve)

####
# constants definition
###

cIL2 <<- 200
cMem <<- 200
cEBV <<- 1000

# To uncomment to reproduce the DAC analysis
#cDAC <<- - numberDAC /log(.1)

probDup<<- 2/3


funODE <- function(t,y, parms){
  
  y[y<1e-8]=0
  ## Parameter to estimate
  TeE = parms["TeE"]
  TrE = parms["TrE"]
  Tr2 = parms["Tr2"]
  Te2 = parms["Te2"]
  TekODC = parms["TekODC"]
  TrkTe = parms["TrkTe"]
  TekEBV = parms["TekEBV"]
  rec = parms["rec"]
  NKkillT=parms["NKkT"]
  
  if( is.na(parms["DACD"]) ) 
  {
    DACD = 0
    cDAC<<-1
  }
  else DACD = parms["DACD"]
  
  ####
  
  ##Begin parameter rates
  
  TrD = 1/24
  TeD = 1/24
  NKD = 1/24
  
  NKVSTeff = NKkillT
  NKVSTreg = NKkillT
  
  nk2 = 1/24

  ## injections at time fixed are defined outside the model
  DACinj = 0 ## it is not MA
  EBVs = 0  ## it is not MA

  ##End parameter rates
  
  ## Begin General transitions
  
  IL2 <-sum(y[il2Pos])
  Treg<-sum(y[tregPos])
  Teff<-sum(y[teffPos])
  EBV<-sum(y[ebvPos])
  NK<-sum(y[nkPos])
  DAC<-sum(y[dacPos])
  ODC<-sum(y[odcPos])
  Mem<-sum(y[memPos])
  
  TotMeet<-sum(y[-c(memPos)]) 
  # ODCandTeff<-ODC+Teff+Treg
  # 
  
  RestingTreg<-sum(y[restregPos])
  RestingTeff<-sum(y[resteffPos])
  
  TimoReg<- (1 - RestingTreg/63 ) * 20
  TimoEff<- (1 - RestingTeff/1687 )* 500
  nkborn <- (1 - NK/375 )* 100
  
  TeffDup = Te2 * ( 1-exp(-IL2/cIL2)  )* ( exp(-DAC/cDAC) )
  TregDup = Tr2 * ( 1-exp(-IL2/cIL2)  )* ( exp(-DAC/cDAC) )
  
  
  TeffActivation = TeE * ( 1 - exp(-EBV/cEBV)  )
  TregActivation = TrE * ( (Teff )/(Teff + EBV+ 1) )
  
  ####### parameter to regulate the Memory cell entry
  
  if(t <= InjEBVTime[2] ) MemE=0
  else MemE = 2* TeE * ( 1-exp(-Mem/cMem)  )
  
  MemActivation = MemE * ( 1- exp(-EBV/cEBV) )
  ###################################################
  
  ##Begin Transition rates
  
  DACDegradation = DACD
  TregDeath  = TrD
  TeffDeath  = TeD
  TeffkillsEBV  = TekEBV
  TregKillsTeff  = TrkTe
  TeffKillsODC_l_le1  = TekODC
  TeffKillsODC_l_le2  = TekODC
  TeffKillsODC_l_le3  = TekODC
  TeffKillsODC_l_le4  = TekODC
  NKkillsTreg  = NKVSTreg 
  NKkillsTeff  = NKVSTeff 
  Remyelinization_l_le2  = rec
  Remyelinization_l_le3  = rec
  Remyelinization_l_le4  = rec
  EBVinj  = EBVs
  NKdup  = nk2
  NKDegradation  = NKD
  DACInjection  = DACinj
  NKarrive  = nkborn
  FromTimoREG  = TimoReg
  FromTimoEFF  = TimoEff
  ##End Transition rates
  ##Places array
  ##Begin Place mapping
  EBV  = y[1]
  Teff  = y[2]
  Treg  = y[3]
  ODC_le1  = y[4]
  ODC_le2  = y[5]
  ODC_le3  = y[6]
  ODC_le4  = y[7]
  ODC_le5  = y[8]
  NK  = y[9]
  IL2  = y[10]
  DAC  = y[11]
  Resting_Teff  = y[12]
  Resting_Treg  = y[13]
  EffectorMemory = y[14]
  ##End Place mapping
  
  # General function velocities
  
  R_TeffDup  =    + 1/TotMeet *TeffDup  * Teff ^1 * IL2 ^1
  R_TeffDup_Sym  =    probDup * R_TeffDup 
  R_TeffDup_Asym  = (1-probDup) * R_TeffDup 
  R_TregDup  =   + 1/TotMeet *TregDup  * Treg ^1 * IL2 ^1
  R_NKdup  =    + 1/TotMeet * NKdup  * NK ^1 * IL2 ^1
  R_TeffkillsEBV  =  + 1/TotMeet * TeffkillsEBV  * EBV ^1 * Teff ^1
  R_TregKillsTeff  =  +  1/TotMeet * TregKillsTeff  * Teff ^1 * Treg ^1
  R_NKkillsTreg  =   + 1/TotMeet *  NKkillsTreg  * Treg ^1 * NK ^1
  R_NKkillsTeff  =   + 1/TotMeet *  NKkillsTeff  * Teff ^1 * NK ^1
  R_TeffKillsODC_l_le1  =  + 1/TotMeet * TeffKillsODC_l_le1  * Teff ^1 * ODC_le2 ^1
  R_TeffKillsODC_l_le2  =  + 1/TotMeet* TeffKillsODC_l_le2  * Teff ^1 * ODC_le3 ^1
  R_TeffKillsODC_l_le3  =  + 1/TotMeet * TeffKillsODC_l_le3  * Teff ^1 * ODC_le4 ^1
  R_TeffKillsODC_l_le4  =  + 1/TotMeet* TeffKillsODC_l_le4  * Teff ^1 * ODC_le5 ^1
  R_TregActivation  =  + TregActivation  * Resting_Treg ^1
  R_TeffActivation =  + TeffActivation * Resting_Teff^1
  R_MemActivation  =  + MemActivation  * EffectorMemory^1
  R_FromTimoEFF  =  + FromTimoEFF 
  R_FromTimoREG  =  + FromTimoREG
  R_EBVinj=EBVinj
  R_DACInjection =  + DACInjection
  
  ## End General transitions
  
##Begin ODE Terms

R_TregDeath =  + TregDeath * Treg^1
R_TeffDeath =  + TeffDeath * Teff^1
R_Remyelinization_l_le2 =  + Remyelinization_l_le2 * ODC_le2^1
R_Remyelinization_l_le3 =  + Remyelinization_l_le3 * ODC_le3^1
R_Remyelinization_l_le4 =  + Remyelinization_l_le4 * ODC_le4^1
R_NKDegradation =  + NKDegradation * NK^1
R_DACDegradation =  + DACDegradation * DAC^1
R_NKarrive = NKarrive
##End ODE Terms

##Begin ODE system
dEBV = -1*R_TeffkillsEBV+1*R_EBVinj
dTeff = -1*R_TeffDeath-1*R_TeffkillsEBV-1*R_TregKillsTeff+1*R_TeffActivation-1*R_NKkillsTeff+1*R_MemActivation+1*R_TeffDup_Sym
dTreg = +1*R_TregActivation-1*R_TregDeath+1*R_TregDup-1*R_NKkillsTreg
dODC_le1 = +1*R_TeffKillsODC_l_le1
dODC_le2 = -1*R_TeffKillsODC_l_le1+1*R_TeffKillsODC_l_le2-1*R_Remyelinization_l_le2
dODC_le3 = -1*R_TeffKillsODC_l_le2+1*R_TeffKillsODC_l_le3+1*R_Remyelinization_l_le2-1*R_Remyelinization_l_le3
dODC_le4 = -1*R_TeffKillsODC_l_le3+1*R_TeffKillsODC_l_le4+1*R_Remyelinization_l_le3-1*R_Remyelinization_l_le4
dODC_le5 = -1*R_TeffKillsODC_l_le4+1*R_Remyelinization_l_le4
dNK = -1*R_NKkillsTreg-1*R_NKkillsTeff+1*R_NKdup-1*R_NKDegradation + R_NKarrive
dIL2 = -1*R_TeffDup_Asym-1*R_TregDup+1*R_TeffActivation-1*R_NKdup+1*R_MemActivation-1*R_TeffDup_Sym
dDAC = +1*R_DACInjection-1*R_DACDegradation
dResting_Teff = -1*R_TeffActivation+1*R_FromTimoEFF
dResting_Treg = -1*R_TregActivation+1*R_FromTimoREG
dEffectorMemory = +1*R_TeffDup_Asym-1*R_MemActivation
list(c(dEBV, dTeff, dTreg, dODC_le1, dODC_le2, dODC_le3, dODC_le4, dODC_le5, dNK, dIL2, dDAC, dResting_Teff, dResting_Treg, dEffectorMemory))
}
##End ODE System

##Setting Markers on Places:

##Setting Markers on Places:
yini <- c(y1 = 0, y2 =0, y3 =0, y4 = 0, y5 = 0, y6 = 0, y7 = 0, y8 = 500, y9 = 375, y10 = 1000, y11 = 0, y12 = 1687, y13 = 63, y14 = 0)

y_names<-c("EBV","Teff","Treg","ODC_le1","ODC_le2","ODC_le3","ODC_le4","ODC_le5","NK","IL2","DAC","Resting_Teff","Resting_Treg","EffectorMemory")


names(yini)= y_names

ebvPos<-c( which(y_names %in% grep("EBV_*", y_names, value=T)) ) 
teffPos<-c( which(y_names %in% grep("^Teff_*", y_names, value=T)) )
odcPos<-c( which(y_names %in% grep("ODC_le5_*", y_names, value=T)))
il2Pos<-c( which(y_names %in% grep("IL2_*", y_names, value=T)))   
tregPos<-c( which(y_names %in% grep("^Treg_*", y_names, value=T)) )
restregPos<-c( which(y_names %in% grep("Resting_Treg_*", y_names, value=T)) )
resteffPos<-c( which(y_names %in% grep("Resting_Teff_*", y_names, value=T)) )
nkPos<-c( which(y_names %in% grep("NK_*", y_names, value=T)) )
dacPos<-c( which(y_names %in% grep("DAC_*", y_names, value=T)) )
memPos<-c( which(y_names %in% grep("EffectorMemory", y_names, value=T)) )

