#
#       Parameter Estimation:
#
# Simple case: no movement so we consider just one block, no NK and no ODC irreversible damage!
# We want to see:
#   1) After 50 days the EBV is gone
#   2) In 14 days the Teff cells reach their max value (20-30 000)
#   3) After 10 days everything comes back to the normality!
#
###################################################################
#This file is automatically generated by Greatspn                 #
#You can report bugs  by sending an e-mail to beccuti@di.unito.it #
###################################################################


library(deSolve)

####
# constants definition
###

cIL2 <<- 200
cMem <<- 200
cEBV <<-1000
cDAC <<- 15

probDup<<- 2/3


funODE <- function(t,y, parms){
  
  y[y<1e-8]=0
  ## Parameter to estimate
  TeE = parms["TeE"]
  TrE = parms["TrE"]
  Tr2 = parms["Tr2"]
  Te2 = parms["Te2"]
  TekODC = parms["TekODC"]
  TrkTe = parms["TrkTe"]
  TekEBV = parms["TekEBV"]
  rec = parms["rec"]
  NKkillT=parms["NKkT"]
  
  ####
  
  ##Begin parameter rates
  DACD =1/(24*60)
  TrD = 1/24
  TeD = 1/24
  NKD = 1/24
  
  NKVSTeff = NKkillT
  NKVSTreg = NKkillT
  
  nk2 = 1/24
  
  DACmoves = 0
  EBVmoves = 0
  Teffmove = 0
  Tregmoves = 0
  
  ## injections at time fixed
  DACinj = 0 ## it is not MA
  EBVs = 0  ## it is not MA
  ILe = 0
  
  ##End parameter rates
  
  ## Begin General transitions
  
  IL2 <-sum(y[il2Pos])
  Treg<-sum(y[tregPos])
  Teff<-sum(y[teffPos])
  EBV<-sum(y[ebvPos])
  NK<-sum(y[nkPos])
  DAC<-sum(y[dacPos])
  ODC<-sum(y[odcPos])
  Mem<-sum(y[memPos])
  
  TotMeet<-sum(y[-c(memPos)]) 
  # ODCandTeff<-ODC+Teff+Treg
  # 
  
  RestingTreg<-sum(y[restregPos])
  RestingTeff<-sum(y[resteffPos])
  
  
  ####### parameter to regulate the Memory cell entry
  
  if(t <= InjEBVTime[2] ) MemE=0
  else MemE = 2* TeE * ( 1-exp(-Mem/cMem)  )
  
  
  ###################################################
  
  TimoReg<- (1 - RestingTreg/63 ) * 20
  TimoEff<- (1 - RestingTeff/1687 )* 500
  nkborn <- (1 - NK/375 )* 100
  
  TeffDup_x_px1_y_py1_z_pz1 = Te2 * ( 1-exp(-IL2/cIL2)  )* ( exp(-DAC/cDAC) )
  TregDup_x_px1_y_py1_z_pz1 = Tr2 * ( 1-exp(-IL2/cIL2)  )* ( exp(-DAC/cDAC) )
  
  TeffActivation_x_px1_y_py1_z_pz1 = TeE * ( 1 - exp(-EBV/cEBV)  )
  TregActivation_x_px1_y_py1_z_pz1 = TrE * ( (Teff )/(Teff + EBV+ 1) )
  
  MemActivation_x_px1_y_py1_z_pz1 = MemE * ( 1- exp(-EBV/cEBV) )
  
  ## End General transitions
  
  
  ##Begin Transition rates
  
  DACDeath_x_px1_y_py1_z_pz1= DACD
  TregDeath_x_px1_y_py1_z_pz1 = TrD
  TeffDeath_x_px1_y_py1_z_pz1 = TeD
  TeffkillsEBV_x_px1_y_py1_z_pz1 = TekEBV
  TregKillsTeff_x_px1_y_py1_z_pz1 = TrkTe
  TeffKillsODC_l_le1_x_px1_y_py1_z_pz1 = TekODC
  TeffKillsODC_l_le2_x_px1_y_py1_z_pz1 = TekODC
  TeffKillsODC_l_le3_x_px1_y_py1_z_pz1 = TekODC
  TeffKillsODC_l_le4_x_px1_y_py1_z_pz1 = TekODC
  NKkillsTreg_x_px1_y_py1_z_pz1 = NKVSTreg 
  NKkillsTeff_x_px1_y_py1_z_pz1 = NKVSTeff 
  Remyelinization_l_le2_x_px1_y_py1_z_pz1 = rec
  Remyelinization_l_le3_x_px1_y_py1_z_pz1 = rec
  Remyelinization_l_le4_x_px1_y_py1_z_pz1 = rec
  
  
  EBVinj_x_px1_y_py1_z_pz1 = EBVs
  
  NKdup_x_px1_y_py1_z_pz1 = nk2
  NKDeath_x_px1_y_py1_z_pz1 = NKD
  DACInjection_x_px1_y_py1_z_pz1 = DACinj
  NKarrive_x_px1_y_py1_z_pz1 = nkborn
  IL2entry_x_px1_y_py1_z_pz1 = ILe
  MovementTeff_k_pz1_p_py1_q_px1_x_px1_y_py1_z_pz1 = Teffmove
  FromTimoREG_x_px1_y_py1_z_pz1 = TimoReg
  MovementEBV_k_pz1_p_py1_q_px1_x_px1_y_py1_z_pz1 = EBVmoves
  MovementTreg_k_pz1_p_py1_q_px1_x_px1_y_py1_z_pz1 = Tregmoves
  DACMovements_k_pz1_p_py1_q_px1_x_px1_y_py1_z_pz1 = DACmoves
  
  FromTimoEFF_x_px1_y_py1_z_pz1 = TimoEff
  ##End Transition rates
  ##Places array
  ##Begin Place mapping
  EBV_px1_py1_pz1 = y[1]
  Teff_px1_py1_pz1 = y[2]
  Treg_px1_py1_pz1 = y[3]
  ODC_le1_px1_py1_pz1 = y[4]
  ODC_le2_px1_py1_pz1 = y[5]
  ODC_le3_px1_py1_pz1 = y[6]
  ODC_le4_px1_py1_pz1 = y[7]
  ODC_le5_px1_py1_pz1 = y[8]
  NK_px1_py1_pz1 = y[9]
  IL2_px1_py1_pz1 = y[10]
  DAC_px1_py1_pz1 = y[11]
  Resting_Teff_px1_py1_pz1 = y[12]
  Resting_Treg_px1_py1_pz1 = y[13]
  EffectorMemory = y[14]
  ##End Place mapping
  
  ##Begin ODE Terms (X all transitions)
  
  R_TeffDup_x_px1_y_py1_z_pz1 =    + 1/TotMeet *TeffDup_x_px1_y_py1_z_pz1 * Teff_px1_py1_pz1^1 * IL2_px1_py1_pz1^1
  R_TeffDup2_x_px1_y_py1_z_pz1 =    probDup * R_TeffDup_x_px1_y_py1_z_pz1
  R_TeffDupMem_x_px1_y_py1_z_pz1 = (1-probDup) * R_TeffDup_x_px1_y_py1_z_pz1
  
  R_TregDup_x_px1_y_py1_z_pz1 =   + 1/TotMeet *TregDup_x_px1_y_py1_z_pz1 * Treg_px1_py1_pz1^1 * IL2_px1_py1_pz1^1
  R_NKdup_x_px1_y_py1_z_pz1 =    + 1/TotMeet * NKdup_x_px1_y_py1_z_pz1 * NK_px1_py1_pz1^1 * IL2_px1_py1_pz1^1
  
  
  R_TeffkillsEBV_x_px1_y_py1_z_pz1 =  + 1/TotMeet * TeffkillsEBV_x_px1_y_py1_z_pz1 * EBV_px1_py1_pz1^1 * Teff_px1_py1_pz1^1
  R_TregKillsTeff_x_px1_y_py1_z_pz1 =  +  1/TotMeet * TregKillsTeff_x_px1_y_py1_z_pz1 * Teff_px1_py1_pz1^1 * Treg_px1_py1_pz1^1
  R_NKkillsTreg_x_px1_y_py1_z_pz1 =   + 1/TotMeet *  NKkillsTreg_x_px1_y_py1_z_pz1 * Treg_px1_py1_pz1^1 * NK_px1_py1_pz1^1
  R_NKkillsTeff_x_px1_y_py1_z_pz1 =   + 1/TotMeet *  NKkillsTeff_x_px1_y_py1_z_pz1 * Teff_px1_py1_pz1^1 * NK_px1_py1_pz1^1
  
  R_TeffKillsODC_l_le1_x_px1_y_py1_z_pz1 =  + 1/TotMeet * TeffKillsODC_l_le1_x_px1_y_py1_z_pz1 * Teff_px1_py1_pz1^1 * ODC_le2_px1_py1_pz1^1
  R_TeffKillsODC_l_le2_x_px1_y_py1_z_pz1 =  + 1/TotMeet* TeffKillsODC_l_le2_x_px1_y_py1_z_pz1 * Teff_px1_py1_pz1^1 * ODC_le3_px1_py1_pz1^1
  R_TeffKillsODC_l_le3_x_px1_y_py1_z_pz1 =  + 1/TotMeet * TeffKillsODC_l_le3_x_px1_y_py1_z_pz1 * Teff_px1_py1_pz1^1 * ODC_le4_px1_py1_pz1^1
  R_TeffKillsODC_l_le4_x_px1_y_py1_z_pz1 =  + 1/TotMeet* TeffKillsODC_l_le4_x_px1_y_py1_z_pz1 * Teff_px1_py1_pz1^1 * ODC_le5_px1_py1_pz1^1
  
  
  R_TregActivation_x_px1_y_py1_z_pz1 =  + TregActivation_x_px1_y_py1_z_pz1 * Resting_Treg_px1_py1_pz1^1
  R_TregDeath_x_px1_y_py1_z_pz1 =  + TregDeath_x_px1_y_py1_z_pz1 * Treg_px1_py1_pz1^1
  R_TeffDeath_x_px1_y_py1_z_pz1 =  + TeffDeath_x_px1_y_py1_z_pz1 * Teff_px1_py1_pz1^1
  
  R_Remyelinization_l_le2_x_px1_y_py1_z_pz1 =  + Remyelinization_l_le2_x_px1_y_py1_z_pz1 * ODC_le2_px1_py1_pz1^1
  R_Remyelinization_l_le3_x_px1_y_py1_z_pz1 =  + Remyelinization_l_le3_x_px1_y_py1_z_pz1 * ODC_le3_px1_py1_pz1^1
  R_Remyelinization_l_le4_x_px1_y_py1_z_pz1 =  + Remyelinization_l_le4_x_px1_y_py1_z_pz1 * ODC_le4_px1_py1_pz1^1
  
  R_TeffActivation_x_px1_y_py1_z_pz1 =  + TeffActivation_x_px1_y_py1_z_pz1 * Resting_Teff_px1_py1_pz1^1
  R_EBVinj_x_px1_y_py1_z_pz1 =  + EBVinj_x_px1_y_py1_z_pz1
  
  R_NKDeath_x_px1_y_py1_z_pz1 =  + NKDeath_x_px1_y_py1_z_pz1 * NK_px1_py1_pz1^1
  R_DACInjection_x_px1_y_py1_z_pz1 =  + DACInjection_x_px1_y_py1_z_pz1
  R_DACDeath_x_px1_y_py1_z_pz1 = + DACDeath_x_px1_y_py1_z_pz1 * DAC_px1_py1_pz1^1
  
  R_NKarrive_x_px1_y_py1_z_pz1 =  + NKarrive_x_px1_y_py1_z_pz1
  
  R_IL2entry_x_px1_y_py1_z_pz1 =  + IL2entry_x_px1_y_py1_z_pz1
  
  R_MovementTeff_k_pz1_p_py1_q_px1_x_px1_y_py1_z_pz1 =  + MovementTeff_k_pz1_p_py1_q_px1_x_px1_y_py1_z_pz1 * Teff_px1_py1_pz1^1
  R_FromTimoREG_x_px1_y_py1_z_pz1 =  + FromTimoREG_x_px1_y_py1_z_pz1
  R_MovementEBV_k_pz1_p_py1_q_px1_x_px1_y_py1_z_pz1 =  + MovementEBV_k_pz1_p_py1_q_px1_x_px1_y_py1_z_pz1 * EBV_px1_py1_pz1^1
  R_MovementTreg_k_pz1_p_py1_q_px1_x_px1_y_py1_z_pz1 =  + MovementTreg_k_pz1_p_py1_q_px1_x_px1_y_py1_z_pz1 * Treg_px1_py1_pz1^1
  R_DACMovements_k_pz1_p_py1_q_px1_x_px1_y_py1_z_pz1 =  + DACMovements_k_pz1_p_py1_q_px1_x_px1_y_py1_z_pz1 * DAC_px1_py1_pz1^1
  R_MemActivation_x_px1_y_py1_z_pz1 =  + MemActivation_x_px1_y_py1_z_pz1 * EffectorMemory^1
  R_FromTimoEFF_x_px1_y_py1_z_pz1 =  + FromTimoEFF_x_px1_y_py1_z_pz1
  
  ##End ODE Terms
  
  ##Begin ODE system
  dEBV_px1_py1_pz1 = -1*R_TeffkillsEBV_x_px1_y_py1_z_pz1+1*R_EBVinj_x_px1_y_py1_z_pz1
  
  dTeff_px1_py1_pz1 = -1*R_TeffDeath_x_px1_y_py1_z_pz1-1*R_TeffkillsEBV_x_px1_y_py1_z_pz1-1*R_TregKillsTeff_x_px1_y_py1_z_pz1+1*R_TeffActivation_x_px1_y_py1_z_pz1-1*R_NKkillsTeff_x_px1_y_py1_z_pz1+1*R_MemActivation_x_px1_y_py1_z_pz1 + R_TeffDup2_x_px1_y_py1_z_pz1
  
  dTreg_px1_py1_pz1 = +1*R_TregActivation_x_px1_y_py1_z_pz1-1*R_TregDeath_x_px1_y_py1_z_pz1+1*R_TregDup_x_px1_y_py1_z_pz1-1*R_NKkillsTreg_x_px1_y_py1_z_pz1
  
  dODC_le1_px1_py1_pz1 = +1*R_TeffKillsODC_l_le1_x_px1_y_py1_z_pz1
  dODC_le2_px1_py1_pz1 = -1*R_TeffKillsODC_l_le1_x_px1_y_py1_z_pz1+1*R_TeffKillsODC_l_le2_x_px1_y_py1_z_pz1-1*R_Remyelinization_l_le2_x_px1_y_py1_z_pz1
  dODC_le3_px1_py1_pz1 = -1*R_TeffKillsODC_l_le2_x_px1_y_py1_z_pz1+1*R_TeffKillsODC_l_le3_x_px1_y_py1_z_pz1+1*R_Remyelinization_l_le2_x_px1_y_py1_z_pz1-1*R_Remyelinization_l_le3_x_px1_y_py1_z_pz1
  dODC_le4_px1_py1_pz1 = -1*R_TeffKillsODC_l_le3_x_px1_y_py1_z_pz1+1*R_TeffKillsODC_l_le4_x_px1_y_py1_z_pz1+1*R_Remyelinization_l_le3_x_px1_y_py1_z_pz1-1*R_Remyelinization_l_le4_x_px1_y_py1_z_pz1
  dODC_le5_px1_py1_pz1 = -1*R_TeffKillsODC_l_le4_x_px1_y_py1_z_pz1+1*R_Remyelinization_l_le4_x_px1_y_py1_z_pz1
  
  dNK_px1_py1_pz1 = +1*R_NKdup_x_px1_y_py1_z_pz1-1*R_NKDeath_x_px1_y_py1_z_pz1+1*R_NKarrive_x_px1_y_py1_z_pz1-1*R_NKkillsTreg_x_px1_y_py1_z_pz1-1*R_NKkillsTeff_x_px1_y_py1_z_pz1
  
  dIL2_px1_py1_pz1 = -1*R_TeffDup_x_px1_y_py1_z_pz1-1*R_TregDup_x_px1_y_py1_z_pz1+1*R_TeffActivation_x_px1_y_py1_z_pz1-1*R_NKdup_x_px1_y_py1_z_pz1+1*R_IL2entry_x_px1_y_py1_z_pz1 + R_MemActivation_x_px1_y_py1_z_pz1
  
  dDAC_px1_py1_pz1 = +1*R_DACInjection_x_px1_y_py1_z_pz1-1*R_DACDeath_x_px1_y_py1_z_pz1
  
  dResting_Teff_px1_py1_pz1 = -1*R_TeffActivation_x_px1_y_py1_z_pz1+1*R_FromTimoEFF_x_px1_y_py1_z_pz1
  dResting_Treg_px1_py1_pz1 = -1*R_TregActivation_x_px1_y_py1_z_pz1+1*R_FromTimoREG_x_px1_y_py1_z_pz1
  
  dEffectorMemory = +1*R_TeffDupMem_x_px1_y_py1_z_pz1-1*R_MemActivation_x_px1_y_py1_z_pz1
  
  list(c(dEBV_px1_py1_pz1, dTeff_px1_py1_pz1, dTreg_px1_py1_pz1, dODC_le1_px1_py1_pz1, dODC_le2_px1_py1_pz1, dODC_le3_px1_py1_pz1, dODC_le4_px1_py1_pz1, dODC_le5_px1_py1_pz1, dNK_px1_py1_pz1, dIL2_px1_py1_pz1, dDAC_px1_py1_pz1, dResting_Teff_px1_py1_pz1, dResting_Treg_px1_py1_pz1, dEffectorMemory))
}
##End ODE System

##Setting Markers on Places:
yini <- c(y1 = 0, y2 =0, y3 =0, y4 = 0, y5 = 0, y6 = 0, y7 = 0, y8 = 500, y9 = 375, y10 = 1000, y11 = 0, y12 = 1687, y13 = 63, y14 = 0)

y_names <- c("EBV_px1_py1_pz1","Teff_px1_py1_pz1","Treg_px1_py1_pz1","ODC_le1_px1_py1_pz1","ODC_le2_px1_py1_pz1","ODC_le3_px1_py1_pz1","ODC_le4_px1_py1_pz1","ODC_le5_px1_py1_pz1","NK_px1_py1_pz1","IL2_px1_py1_pz1","DAC_px1_py1_pz1","Resting_Teff_px1_py1_pz1","Resting_Treg_px1_py1_pz1","EffectorMemory")

names(yini)= y_names

ebvPos<-c( which(y_names %in% grep("EBV_*", y_names, value=T)) ) 
teffPos<-c( which(y_names %in% grep("^Teff_*", y_names, value=T)) )
odcPos<-c( which(y_names %in% grep("ODC_le5_*", y_names, value=T)))
il2Pos<-c( which(y_names %in% grep("IL2_*", y_names, value=T)))   
tregPos<-c( which(y_names %in% grep("^Treg_*", y_names, value=T)) )
restregPos<-c( which(y_names %in% grep("Resting_Treg_*", y_names, value=T)) )
resteffPos<-c( which(y_names %in% grep("Resting_Teff_*", y_names, value=T)) )
nkPos<-c( which(y_names %in% grep("NK_*", y_names, value=T)) )
dacPos<-c( which(y_names %in% grep("DAC_*", y_names, value=T)) )
memPos<-c( which(y_names %in% grep("EffectorMemory", y_names, value=T)) )


