
###################################################################
#This file is automatically generated by Greatspn                 #
#You can report bugs  by sending an e-mail to beccuti@di.unito.it #
###################################################################
source("transition.R")

library(deSolve)

#Times <- seq(from = 0, to = FinalTime, by = step)


##End parameter rates

##Begin Transition rates
TregDeath = TrD
TeffDeath = TeD
Remyelinization_l_le2 = rec
Remyelinization_l_le3 = rec
Remyelinization_l_le4 = rec
NKDegradation = NKD
DACDegradation = DACD
##End Transition rates

##Begin map indexing the places to y 

NumPlaces= seq(1:17)

names(NumPlaces)= c( "EBV","Teff","Treg","ODC_le1","ODC_le2","ODC_le3","ODC_le4","ODC_le5","NK","IL2","DAC","Resting_Teff","Resting_Treg","EffectorMemory","Resting_Treg_temp","Resting_Teff_temp","NK_temp")

 ##End Place indexes mapping

funODE <- function(t,y, parms){

##Places array
##Begin Place mapping
EBV = y[1]
Teff = y[2]
Treg = y[3]
ODC_le1 = y[4]
ODC_le2 = y[5]
ODC_le3 = y[6]
ODC_le4 = y[7]
ODC_le5 = y[8]
NK = y[9]
IL2 = y[10]
DAC = y[11]
Resting_Teff = y[12]
Resting_Treg = y[13]
EffectorMemory = y[14]
Resting_Treg_temp = y[15]
Resting_Teff_temp = y[16]
NK_temp = y[17]
##End Place mapping

##Begin ODE Terms (X all transitions)
R_TregActivation = TregActivation(y,"TregActivation",NumPlaces,t,InputPlaces=c("Teff", "Resting_Treg"), card=c(1, 1) )
R_TregDeath =  + TregDeath * Treg^1
R_TeffDeath =  + TeffDeath * Teff^1
R_TeffkillsEBV = Killing(y,"TeffkillsEBV",NumPlaces,t,InputPlaces=c("EBV", "Teff"), card=c(1, 1) )
R_TregKillsTeff = Killing(y,"TregKillsTeff",NumPlaces,t,InputPlaces=c("Teff", "Treg"), card=c(1, 1) )
R_TeffKillsODC_l_le1 = KillingODC(y,"TeffKillsODC_l_le1",NumPlaces,t,InputPlaces=c("Teff", "ODC_le2"), card=c(1, 1) )
R_TeffKillsODC_l_le2 = KillingODC(y,"TeffKillsODC_l_le2",NumPlaces,t,InputPlaces=c("Teff", "ODC_le3"), card=c(1, 1) )
R_TeffKillsODC_l_le3 = KillingODC(y,"TeffKillsODC_l_le3",NumPlaces,t,InputPlaces=c("Teff", "ODC_le4"), card=c(1, 1) )
R_TeffKillsODC_l_le4 = KillingODC(y,"TeffKillsODC_l_le4",NumPlaces,t,InputPlaces=c("Teff", "ODC_le5"), card=c(1, 1) )
R_Remyelinization_l_le2 =  + Remyelinization_l_le2 * ODC_le2^1
R_Remyelinization_l_le3 =  + Remyelinization_l_le3 * ODC_le3^1
R_Remyelinization_l_le4 =  + Remyelinization_l_le4 * ODC_le4^1
R_TeffDup_Asym = TeffDup(y,"TeffDup_Asym",NumPlaces,t,InputPlaces=c("Teff", "IL2", "DAC"), card=c(1, 1, 1) )
R_TregDup = TregDup(y,"TregDup",NumPlaces,t,InputPlaces=c("Treg", "IL2", "DAC"), card=c(1, 1, 1) )
R_TeffActivation = TeffActivation(y,"TeffActivation",NumPlaces,t,InputPlaces=c("EBV", "Resting_Teff"), card=c(1, 1) )
R_NKkillsTreg = Killing(y,"NKkillsTreg",NumPlaces,t,InputPlaces=c("Treg", "NK"), card=c(1, 1) )
R_NKkillsTeff = Killing(y,"NKkillsTeff",NumPlaces,t,InputPlaces=c("Teff", "NK"), card=c(1, 1) )
R_NKdup = NKdup(y,"NKdup",NumPlaces,t,InputPlaces=c("NK", "IL2", "NK_temp"), card=c(1, 1, 1) )
R_NKDegradation =  + NKDegradation * NK^1
R_NKarrive = NKBorn(y,"NKarrive",NumPlaces,t,InputPlaces=c("NK_temp"), card=c(1) )
R_FromTimoREG = TimoReg(y,"FromTimoREG",NumPlaces,t,InputPlaces=c("Resting_Treg_temp"), card=c(1) )
R_MemActivation = MemActivation(y,"MemActivation",NumPlaces,t,InputPlaces=c("EBV", "EffectorMemory"), card=c(1, 1) )
R_FromTimoEFF = TimoEff(y,"FromTimoEFF",NumPlaces,t,InputPlaces=c("Resting_Teff_temp"), card=c(1) )
R_TeffDup_Sym = TeffDup(y,"TeffDup_Sym",NumPlaces,t,InputPlaces=c("Teff", "IL2", "DAC"), card=c(1, 1, 1) )
R_DACDegradation =  + DACDegradation * DAC^1
##End ODE Terms

##Begin ODE system
dEBV = -1*R_TeffkillsEBV
dTeff = -1*R_TeffDeath-1*R_TeffkillsEBV-1*R_TregKillsTeff+1*R_TeffActivation-1*R_NKkillsTeff+1*R_MemActivation+1*R_TeffDup_Sym
dTreg = +1*R_TregActivation-1*R_TregDeath+1*R_TregDup-1*R_NKkillsTreg
dODC_le1 = +1*R_TeffKillsODC_l_le1
dODC_le2 = -1*R_TeffKillsODC_l_le1+1*R_TeffKillsODC_l_le2-1*R_Remyelinization_l_le2
dODC_le3 = -1*R_TeffKillsODC_l_le2+1*R_TeffKillsODC_l_le3+1*R_Remyelinization_l_le2-1*R_Remyelinization_l_le3
dODC_le4 = -1*R_TeffKillsODC_l_le3+1*R_TeffKillsODC_l_le4+1*R_Remyelinization_l_le3-1*R_Remyelinization_l_le4
dODC_le5 = -1*R_TeffKillsODC_l_le4+1*R_Remyelinization_l_le4
dNK = -1*R_NKkillsTreg-1*R_NKkillsTeff+1*R_NKdup-1*R_NKDegradation+1*R_NKarrive
dIL2 = -1*R_TeffDup_Asym-1*R_TregDup+1*R_TeffActivation-1*R_NKdup+1*R_MemActivation-1*R_TeffDup_Sym
dDAC = -1*R_DACDegradation
dResting_Teff = -1*R_TeffActivation+1*R_FromTimoEFF
dResting_Treg = -1*R_TregActivation+1*R_FromTimoREG
dEffectorMemory = +1*R_TeffDup_Asym-1*R_MemActivation
dResting_Treg_temp = +1*R_TregActivation-1*R_FromTimoREG
dResting_Teff_temp = +1*R_TeffActivation-1*R_FromTimoEFF
dNK_temp = +1*R_NKkillsTreg+1*R_NKkillsTeff-1*R_NKdup+1*R_NKDegradation-1*R_NKarrive
list(c(dEBV, dTeff, dTreg, dODC_le1, dODC_le2, dODC_le3, dODC_le4, dODC_le5, dNK, dIL2, dDAC, dResting_Teff, dResting_Treg, dEffectorMemory, dResting_Treg_temp, dResting_Teff_temp, dNK_temp))
}
##End ODE System

##Setting Markers on Places:
yini <- c(y1 = 0, y2 =0, y3 =0, y4 = 0, y5 = 0, y6 = 0, y7 = 0, y8 = 500, y9 = 375, y10 = 1000, y11 = 0, y12 = 1687, y13 = 63, y14 = 0, y15 = 0, y16 = 0, y17 = 0)
